---
title: |
  Code Notebook
subtitle: |
  How does reported partisan attachement influence affective polarization?: A comparative study of 25 European democracies
date: last-modified
date-format: MMMM D, YYYY
format:
  html:
    toc: true
    code-fold: true
    code-tools: true
execute:
  echo: true
  warning: true
  eval: true
  message: true
---

# Setup

```{r}
#| label: setup

# To track render duration
start_time <- Sys.time()

# set width of console output
options(width = 80)


# Install and load required packages
p_required <- c(
  "tidyverse",
  "here",
  "haven",
  "sessioninfo"
)
packages <- rownames(installed.packages())
p_to_install <- p_required[!(p_required %in% packages)]
if (length(p_to_install) > 0) {
  install.packages(p_to_install)
}
sapply(p_required, require, character.only = TRUE)
rm(p_required, p_to_install, packages)
```

# Load EES Data

```{r}
#| label: load-ees-data

ees_2004 <- read_dta(
  here(
    "data",
    "01_raw",
    "ees",
    "2004",
    "ZA4566.dta"
  )
)

ees_2009 <- read_sav(
  here(
    "data",
    "01_raw",
    "ees",
    "2009",
    "ZA5055_v1-1-1.sav"
  )
)

ees_2014 <- read_dta(
  here(
    "data",
    "01_raw",
    "ees",
    "2014",
    "ZA5160_v4-1-0.dta"
  )
)

ess_2019 <- read_dta(
  here(
    "data",
    "01_raw",
    "ees",
    "2019",
    "ZA7581_v2-0-1.dta"
  )
)

ess_2024 <- read_csv2(
  here(
    "data",
    "01_raw",
    "ees",
    "2024",
    "ZA8868_v1-0-0.csv"
  )
)
```

# Select PID and other key Variables

```{r}
#| label: select

# 2024

ess_2024 <- ess_2024 |>
  select(
    year,
    resp_id,
    countrycode,
    country_alpha2,
    q19
  )
```

# Join to Long Format 

# Plot Share of Respondents reporting PID (incl. other), denying PID and Don't Know

# Session Info

```{r}
#| label: session-info

session_info()
```


# Render Time

```{r}
#| label: render-time

end_time <- Sys.time()

rendering_time <- end_time - start_time

message(paste(
  "Document rendered in:",
  round(as.numeric(rendering_time, units = "secs"), 2),
  "seconds.
"
))
```


  
