---
title: |
  Code Notebook
subtitle: |
  How does reported partisan attachement influence affective polarization?: A comparative study of 25 European democracies
author:
  - name: Tristan Muno
    email: tristan.muno@uni-mannheim.de
    affiliations:
      - name: University of Mannheim
        department: School of Social Sciences
date: last-modified
date-format: MMMM D, YYYY
format:
  html:
    toc: true
    code-fold: true
    code-tools: true
    embed-resources: true
execute:
  echo: true
  warning: true
  eval: true
  message: true
---

# Setup

```{r}
#| label: setup

# To track render duration
start_time <- Sys.time()

# set width of console output
options(width = 80)


# Install and load required packages
p_required <- c(
  "tidyverse",
  "here",
  "brms",
  "sessioninfo"
)
packages <- rownames(installed.packages())
p_to_install <- p_required[!(p_required %in% packages)]
if (length(p_to_install) > 0) {
  install.packages(p_to_install)
}
sapply(p_required, require, character.only = TRUE)
rm(p_required, p_to_install, packages)
```

```{r}
#| label: load-compiled-models

load(
  here("data", "02_processed", "models", "compiled_naive_d.RData")
)

load(
  here("data", "02_processed", "models", "compiled_naive_t.RData")
)

load(
  here("data", "02_processed", "models", "compiled_naive_cov_d.RData")
)

load(
  here("data", "02_processed", "models", "compiled_naive_cov_t.RData")
)

load(
  here("data", "02_processed", "models", "compile_base_d.RData")
)

load(
  here("data", "02_processed", "models", "compile_base_t.RData")
)

load(
  here("data", "02_processed", "models", "compile_cov_d.RData")
)

load(
  here("data", "02_processed", "models", "compile_cov_t.RData")
)
```

# Prior predictive checks

```{r}
#| label: prior-predictive-check-naive-d

Sys.setenv(RSTUDIO = 1)

pp_check(update(
  compiled_naive_d,
  iter = 1000,
  cores = 4,
  sample_prior = "only"
))
```

```{r}
#| label: prior-predictive-check-naive-t

pp_check(update(
  compiled_naive_t,
  iter = 1000,
  cores = 4,
  sample_prior = "only"
))
```

```{r}
#| label: prior-predictive-check-naive-cov-d

pp_check(update(
  compiled_naive_cov_d,
  iter = 1000,
  cores = 4,
  sample_prior = "only"
))
```

```{r}
#| label: prior-predictive-check-naive-cov-t

pp_check(update(
  compiled_naive_cov_t,
  iter = 1000,
  cores = 4,
  sample_prior = "only"
))
```

```{r}
#| label: prior-predictive-check-base-d

pp_check(update(
  compiled_base_d,
  iter = 1000,
  cores = 4,
  sample_prior = "only"
))
```

```{r}
#| label: prior-predictive-check-base-t

pp_check(update(
  compiled_base_t,
  iter = 1000,
  cores = 4,
  sample_prior = "only"
))
```

```{r}
#| label: prior-predictive-check-cov-d

pp_check(update(
  compiled_cov_d,
  iter = 1000,
  cores = 4,
  sample_prior = "only"
))
```

```{r}
#| label: prior-predictive-check-cov-t

pp_check(update(
  compiled_cov_t,
  iter = 1000,
  cores = 4,
  sample_prior = "only"
))
```

# Session Info

```{r}
#| label: session-info

session_info()
```


# Render Time

```{r}
#| label: render-time

end_time <- Sys.time()

rendering_time <- end_time - start_time

message(paste(
  "Document rendered in:",
  round(as.numeric(rendering_time, units = "secs"), 2),
  "seconds.
"
))
```


  
