---
title: |
  Code Notebook
subtitle: |
  How does reported partisan attachement influence affective polarization?: A comparative study of 25 European democracies
date: last-modified
date-format: MMMM D, YYYY
format:
  html:
    toc: true
    code-fold: true
    code-tools: true
execute:
  echo: true
  warning: true
  eval: true
  message: true
---

# Setup

```{r}
#| label: setup

# To track render duration
start_time <- Sys.time()

# set width of console output
options(width = 80)


# Install and load required packages
p_required <- c(
  "tidyverse",
  "here",
  "brms",
  "sessioninfo"
)
packages <- rownames(installed.packages())
p_to_install <- p_required[!(p_required %in% packages)]
if (length(p_to_install) > 0) {
  install.packages(p_to_install)
}
sapply(p_required, require, character.only = TRUE)
rm(p_required, p_to_install, packages)
```

# Load Data

```{r}
#| label: load-data

eu25games2019 <- readRDS(
  here(
    "data",
    "03_final",
    "eu25games2019.rds"
  )
)

thermo_long <- readRDS(
  here(
    "data",
    "03_final",
    "thermo_long.rds"
  )
)

```

# Prepare Data

```{r}
#| label: prepare-dat

# Outcome 1: Thermometer Scores
thermo2model <- thermo_long |>
  mutate(
    copartisan = if_else(
      der_partisan_anchor == thermo_party,
      1,
      0
    )
  ) |>
  na.omit()

# Outcome 2: Game allocation

```


# Session Info

```{r}
#| label: session-info

session_info()
```


# Render Time

```{r}
#| label: render-time

end_time <- Sys.time()

rendering_time <- end_time - start_time

message(paste(
  "Document rendered in:",
  round(as.numeric(rendering_time, units = "secs"), 2),
  "seconds.
"
))
```


  
