---
title: |
  Code Notebook
subtitle: |
  How does reported partisan attachement influence affective polarization?: A comparative study of 25 European democracies
author:
  - name: Tristan Muno
    email: tristan.muno@uni-mannheim.de
    affiliations:
      - name: University of Mannheim
        department: School of Social Sciences
date: last-modified
date-format: MMMM D, YYYY
format:
  html:
    toc: true
    code-fold: true
    code-tools: true
execute:
  echo: true
  warning: true
  eval: true
  message: true
---

# Setup

```{r}
#| label: setup

# To track render duration
start_time <- Sys.time()

# set width of console output
options(width = 80)


# Install and load required packages
p_required <- c(
  "tidyverse",
  "here",
  "janitor",
  "dagitty",
  "ggdag",
  "lme4",
  "brms",
  "sessioninfo"
)
packages <- rownames(installed.packages())
p_to_install <- p_required[!(p_required %in% packages)]
if (length(p_to_install) > 0) {
  install.packages(p_to_install)
}
sapply(p_required, require, character.only = TRUE)
rm(p_required, p_to_install, packages)
```

```{r}
#| label: load-data

load(
  here(
    "data",
    "02_processed",
    "eu25games2019.RData"
  )
)
```

# Model DAG

```{r}
#| label: fig-dag
#| fig-cap: "Directed acyclical graph (DAG) of the causal data-generating process. Respondents have a partisan anchor $A$, representing the party they feel attached to (explicit partisans) or (intend to) vote for (implicit partisans). Partisan type $T$ (explicit vs. implicit) is only defined for respondents with a partisan anchor and is thus a child node of $A$. The conjoint design randomizes all profile attributes $Z$. The partisan profile cue $Z^{party}$ combines with $A$ to generate the partisan relationship category $R = f(A, Z^{party}), which determines whether the profile is interpreted as a co-partisan, out-partisan, or neutral. Other randomized profile cues $Z^{other}$ affect the outcome $Y$ directly. Token allocations $Y$ are influenced by both $R$ and $Z^{other}$, with the effect of $R$ theorized to be conditional on $T$. Because $T$ is observational, potential confounders $C$ may affect both $T$ and $Y$, highlighting the assumptions required for causal interpretation."
#| fig-dpi: 500

dag <- dagitty(
  "dag {
\"Z1\" [pos=\"0, 1\"]
A [pos=\"0, 2\"]
C [pos=\"2, 1\"]
R [pos=\"1 ,1\"]
T [exposure,pos=\"1 , 2\"]
Y [outcome,pos=\"1 ,0\"]
Z [pos=\"0 ,0\"]
\"Z1\" -> R
A -> R
A -> T
C -> T
C -> Y
R -> Y
T -> R
Z -> Y
}"
)

tidy_dag <- tidy_dagitty(dag)

label_mapping <- tibble(
  name = c("A", "C", "R", "T", "Y", "Z", "Z1"),
  new_label = c(
    "A[i]",
    "C[i]",
    "R[r*i]",
    "T[i]",
    "Y[ri]",
    "Z[r]^{other}",
    "Z[r]^{party}"
  )
)

tidy_dag <- tidy_dag |>
  left_join(
    label_mapping,
    by = join_by(name)
  )

ggdag(tidy_dag) +
  geom_dag_node() +
  geom_dag_text(aes(label = new_label), parse = T) +
  geom_dag_edges() +
  theme_dag()
```

# Model Formula

What to model as random slopes, what to model as random intercepts????

```{r}
#| label: model-formula

formula_base <-
  # outcome: tokens allocated
  cj_token ~
    # main variable of interest
    der_partisan_type +
    # partisan relationship variable
    der_partisan_relationship +
    # interaction term for conditional effects
    der_partisan_type *
      der_partisan_relationship +

    # conjoint controls
    cj_age_en +
    cj_class_en +
    cj_sex_en +
    cj_reli_en +
    # only in dictator game: eu pos as additional treatment
    cj_eupos_shown +
    # round of game
    meta_round +
    # wave of survey
    meta_wave +

    # random intercept + slope of T, R, and TxR at country level
    (1 + der_partisan_type * der_partisan_relationship | meta_country) +
    # random intercept + slope of T at party-within-country level
    (1 +
      der_partisan_type * der_partisan_relationship |
      meta_country:der_partisan_anchor_name) +
    # respondent random intercept nested in party-within-country
    (1 | meta_country:der_partisan_anchor_name:meta_pid)

formula_control

```

```{r}
#| label: code-1
#| eval: false

# start your code here
test <- lmer(
  formula = formula_base,
  data = eu25games2019 |>
    filter(meta_game == "dict" & der_conational == "co-national")
)

summary(test)
vcov(test)


summary(lmer(
  formula = cj_token ~ der_partisan_type *
    der_partisan_relationship +
    (1 + der_partisan_type | meta_country) +
    (1 + der_partisan_type | meta_country:der_partisan_anchor_name) +
    (1 | meta_country:der_partisan_anchor_name:meta_pid),
  data = eu25games2019 |>
    filter(meta_game == "trust" & der_conational == "co-national")
))
```







# Model Starting Values

# Model Settings

# Estimation

# Saving

# Session Info

```{r}
#| label: session-info

session_info()
```


# Render Time

```{r}
#| label: render-time

end_time <- Sys.time()

rendering_time <- end_time - start_time

message(paste(
  "Document rendered in:",
  round(as.numeric(rendering_time, units = "secs"), 2),
  "seconds.
"
))
```


  
