---
title: |
  Code Notebook
subtitle: |
  How does reported partisan attachement influence affective polarization?: A comparative study of 25 European democracies
author:
  - name: Tristan Muno
    email: tristan.muno@uni-mannheim.de
    affiliations:
      - name: University of Mannheim
        department: School of Social Sciences
date: last-modified
date-format: MMMM D, YYYY
format:
  html:
    toc: true
    code-fold: true
    code-tools: true
    embed-resources: true
execute:
  echo: true
  warning: true
  eval: true
  message: true
---

# Setup

```{r}
#| label: setup

# To track render duration
start_time <- Sys.time()

# set width of console output
options(width = 80)


# Install and load required packages
p_required <- c(
  "tidyverse",
  "here",
  "brms",
  "sessioninfo"
)
packages <- rownames(installed.packages())
p_to_install <- p_required[!(p_required %in% packages)]
if (length(p_to_install) > 0) {
  install.packages(p_to_install)
}
sapply(p_required, require, character.only = TRUE)
rm(p_required, p_to_install, packages)
```

```{r}
#| label: load-compiled-models

load(
  here("data", "02_processed", "models", "compiled_naive_d.RData")
)

load(
  here("data", "02_processed", "models", "compiled_naive_t.RData")
)

load(
  here("data", "02_processed", "models", "compiled_naive_cov_d.RData")
)

load(
  here("data", "02_processed", "models", "compiled_naive_cov_t.RData")
)

load(
  here("data", "02_processed", "models", "compile_base_d.RData")
)

load(
  here("data", "02_processed", "models", "compile_base_t.RData")
)

load(
  here("data", "02_processed", "models", "compile_cov_d.RData")
)

load(
  here("data", "02_processed", "models", "compile_cov_t.RData")
)
```


```{r, message = NA}
#| label: fit-settings
Sys.setenv(RSTUDIO = 1)

n_chains <- 4
n_iter <- 5000
n_burnin <- 3500
n_cores <- 4
```


```{r, message = NA}
#| label: fit-model-naive-d

message(paste("Fitting bfit_naive_d at", Sys.time()))
bfit_naive_d <- update(
  compiled_naive_d,
  iter = n_iter,
  warmup = n_burnin,
  chains = n_chains,
  cores = n_cores
)

message("Saving posterior draws...\n")
save(
  bfit_naive_d,
  file = here("data", "03_final", "models", "bfit_naive_d.RData")
)
```

```{r, message = NA}
#| label: fit-model-naive-t

message(paste("Fitting bfit_naive_t at", Sys.time()))
bfit_naive_t <- update(
  compiled_naive_t,
  iter = n_iter,
  warmup = n_burnin,
  chains = n_chains,
  cores = n_cores
)

message("Saving posterior draws...\n")
save(
  bfit_naive_d,
  file = here("data", "03_final", "models", "bfit_naive_t.RData")
)
```

```{r, message = NA}
#| label: fit-model-naive-cov-d

message(paste("Fitting bfit_naive_cov_d at", Sys.time()))
bfit_naive_cov_d <- update(
  compiled_naive_cov_d,
  iter = n_iter,
  warmup = n_burnin,
  chains = n_chains,
  cores = n_cores,
  refresh = 10
)

message("Saving posterior draws...\n")
save(
  bfit_naive_cov_d,
  file = here("data", "03_final", "models", "bfit_naive_cov_d.RData")
)
```

```{r, message = NA}
#| label: fit-model-naive-cov-t

message(paste("Fitting bfit_naive_cov_t at", Sys.time()))
bfit_naive_cov_t <- update(
  compiled_naive_cov_t,
  iter = n_iter,
  warmup = n_burnin,
  chains = n_chains,
  cores = n_cores,
  refresh = 10
)

message("Saving posterior draws...\n")
save(
  bfit_naive_cov_t,
  file = here("data", "03_final", "models", "bfit_naive_cov_t.RData")
)
```


```{r, message = NA}
#| label: fit-model-base-d
#| eval: false

message(paste("Fitting bfit_base_d at", Sys.time()))
bfit_base_d <- update(
  compiled_base_d,
  iter = n_iter,
  warmup = n_burnin,
  chains = n_chains,
  cores = n_cores,
  refresh = 10
)

message("Saving posterior draws...\n")
save(
  bfit_base_d,
  file = here("data", "03_final", "models", "bfit_base_d.RData")
)
```

```{r, message = NA}
#| label: fit-model-base-t
#| eval: false

message(paste("Fitting bfit_base_t at", Sys.time()))
bfit_base_t <- update(
  compiled_base_t,
  iter = n_iter,
  warmup = n_burnin,
  chains = 4,
  cores = 4,
  refresh = 10
)
message("Saving posterior draws...\n")
save(
  bfit_base_t,
  file = here("data", "03_final", "models", "bfit_base_t.RData")
)
```

```{r, message = NA}
#| label: fit-model-cov-d
#| eval: false

message(paste("Fitting bfit_cov_d at", Sys.time()))
bfit_cov_d <- update(
  compiled_cov_d,
  iter = n_iter,
  warmup = n_burnin,
  chains = 4,
  cores = 4,
  refresh = 10
)
message("Saving posterior draws...\n")
save(
  bfit_cov_d,
  file = here("data", "03_final", "models", "bfit_cov_d.RData")
)
```

```{r, message = NA}
#| label: fit-model-cov-t
#| eval: false

message(paste("Fitting bfit_cov_t at", Sys.time()))
bfit_cov_t <- update(
  compiled_cov_t,
  iter = n_iter,
  warmup = n_burnin,
  chains = 4,
  cores = 4,
  refresh = 10
)
message("Saving posterior draws...\n")
save(
  bfit_cov_t,
  file = here("data", "03_final", "models", "bfit_cov_t.RData")
)
```

# Session Info

```{r}
#| label: session-info

session_info()
```


# Render Time

```{r}
#| label: render-time

end_time <- Sys.time()

rendering_time <- end_time - start_time

message(paste(
  "Document rendered in:",
  round(as.numeric(rendering_time, units = "secs"), 2),
  "seconds.
"
))
```