---
title: |
  Code Notebook
subtitle: |
  How does reported partisan attachement influence affective polarization?: A comparative study of 25 European democracies
author:
  - name: Tristan Muno
    email: tristan.muno@uni-mannheim.de
    affiliations:
      - name: University of Mannheim
        department: School of Social Sciences
date: last-modified
date-format: MMMM D, YYYY
format:
  html:
    toc: true
    code-fold: true
    code-tools: true
    embed-resources: true
execute:
  echo: true
  warning: true
  eval: true
  message: true
---

# Setup

```{r}
#| label: setup

# To track render duration
start_time <- Sys.time()

# set width of console output
# options(width = 80)

# Install and load required packages
p_required <- c(
  "tidyverse",
  "here",
  "brms",
  "performance",
  "broom.mixed",
  "tidybayes",
  "ggpubr",
  "knitr",
  "sessioninfo"
)
packages <- rownames(installed.packages())
p_to_install <- p_required[!(p_required %in% packages)]
if (length(p_to_install) > 0) {
  install.packages(p_to_install)
}
sapply(p_required, require, character.only = TRUE)
rm(p_required, p_to_install, packages)
```

# Load models

```{r}
#| label: load-models

load(here("data", "03_final", "models", "bfit_naive_d.RData"))

load(here("data", "03_final", "models", "bfit_naive_t.RData"))

load(here("data", "03_final", "models", "bfit_naive_cov_d.RData"))

load(here("data", "03_final", "models", "bfit_naive_cov_t.RData"))

load(here("data", "03_final", "models", "bfit_base_d.RData"))

load(here("data", "03_final", "models", "bfit_base_t.RData"))

load(here("data", "03_final", "models", "bfit_cov_d.RData"))

load(here("data", "03_final", "models", "bfit_cov_t.RData"))

```

# Model summary

```{r, message = NA}
#| label: model-summary

all_models <- ls(pattern = "^bfit")

fit_summary_fun <- function(model_name) {
  model_fit <- get(model_name)

  message(paste("Calling summary() on", model_name, "\n"))
  print(summary(model_fit, rhat = T, ess = T))

  message(paste("Calling broom.mixed::tidy() on", model_name, "\n"))
  tidy(model_fit, rhat = T, ess = T)

  message(paste("Generating traceplots for", model_name, "\n"))
  plot(model_fit, ask = FALSE)

  message(paste("Generating pp_check for", model_name, "\n"))
  print(pp_check(model_fit, ndraws = 100))
}

for (i in all_models) {
  message(paste("Processing model", i, "\n"))
  fit_summary_fun(i)
}


```

# Model fit

```{r}
#| label: assess-model-fit-loo

loo(
  bfit_naive_d
)


loo(
  bfit_naive_t
)


loo(
  bfit_naive_cov_d
)


loo(
  bfit_naive_cov_t
)

loo(
  bfit_base_d
)


loo(
  bfit_base_t
)

loo(
  bfit_cov_d
)

loo(
  bfit_cov_t
)
```

```{r}
#| label: variance-decomposition
variance_decomposition(bfit_base_d)

variance_decomposition(bfit_base_t)

variance_decomposition(bfit_cov_d)

variance_decomposition(bfit_cov_t)
```


# Session Info

```{r}
#| label: session-info

session_info()
```


# Render Time

```{r}
#| label: render-time

end_time <- Sys.time()

rendering_time <- end_time - start_time

message(paste(
  "Document rendered in:",
  round(as.numeric(rendering_time, units = "secs"), 2),
  "seconds.
"
))
```